### ISSUE TITLE
Activate upon opening the Terminal?

### ISSUE THREAD

**Issue by Gabriel-p** [sotte/conda_auto_activate#1]
This script works great when one cds into a folder with a `.condaauto` file. But it does not work when the Terminal is opened and the folder is already cd'd into.

A `pyenv-virtualenv` can be activated like that for example, using (I use `zsh`):

```
# Load pyenv automatically by adding
# the following to ~/.zshrc:
export PATH="/home/gabriel/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by Gabriel-p** [comment]
Just realized how to do this. I simply add a line to the `.sh.  file:

    cd .

to reload the folder.

**Comment by sotte** [comment]
`cd .` "solves" the issue, true. Glad you found the workaround.
